[WIP] Time-invariant event log
dedis/cothority pull request #2382
Opened 2020-09-28 05:38 UTC by pierluca

This pull requests deals with #2376 and adds a few documentation fixes.
It makes the event log contract time-invariant by referring exclusively to the current block timestamp rather than `time.Now()`

I'm still looking into the unit-tests.

🙅‍ Friendly checklist:

- [ ] 0. Code comments are added (or updated) when/where needed and explain the WHY of the code.
- [ ] 1. Design choices, user documentation and any additional doc are added (or updated) in READMEs.
- [ ] 2. Any new behaviour is tested and small units of code that can be are unit tested.
- [ ] 3. Code comments are added on tests to explain what they do.
- [ ] 4. Errors are systematically wrapped with a meaningful message using `xerrors.Errorf` and the `%v` verb.
- [ ] 5. Hard limit of 80 chars is always respected.
- [ ] 6. Changes are backward compatible.
- [ ] 7. Indentation level does not exceed 5, although 4 is already suspicious.
- [ ] 8. Functions, files, and packages are kept to a manageable size and decomposed into smaller units if needed.
- [ ] 9. There are no magic values.

2020-09-28 10:29 UTC, ineiti commented
Draft-comments: I started doing 2 separate PRs for separating:
- comments changes that don't change the code
- actual implementation of what I'm doing
Of course I do this only once I'm done with the PR itself...

2020-09-30 14:39 UTC, pierluca commented
I'm waiting for Travis to work, based on : https://github.com/dedis/cothority/pull/2383 and https://github.com/dedis/cothority/issues/2367

2020-09-30 14:44 UTC, ineiti requested changes
Are there tests for this change?

2020-09-30 14:44 UTC, ineiti commented on eventlog/service.go
> +	// Check the timestamp of the event: it should never be in the future beyond the current block,
you accept `4 * config.BlockInterval`, which is fine, but doesn't match your comment here.

2020-09-30 14:44 UTC, ineiti commented on eventlog/service.go
> +const eventDelayTolerance = time.Duration(-60 * 1e9)
```suggestion
const eventDelayTolerance = time.Minute
```

And reverse the comment to say _before_, as well as changing the code.

2020-10-05 09:26 UTC, ineiti commented
You can rebase to master, the updates to the testing framework should make it work more reliable now. And if new tests fail, it'll be easier to make them pass...

2020-10-05 09:27 UTC, ineiti commented
In fact the latest travis test failed because of an error in coveralls...

2020-10-19 14:24 UTC, ineiti commented
@pierluca bumping this, as the `byzcoin.BCTest` is now in `master` and produces quite stable tests.

2020-10-19 14:33 UTC, pierluca commented
Thanks for the information @ineiti.
I'm committed to seeing this through, but it's not my #1 priority right now.
I'll come back to this as soon as I can find some spare time.

2021-03-10 13:48 UTC, ineiti commented
Is this something you think working on, or should it be closed? You might want to delegate it ;)

2021-04-06 15:47 UTC, pierluca commented
Considering Cothority is reaching C4DT support's end-of-life in April 2022 and that this feature is not currently used by any production system, I'm closing this PR. I'd be happy to pick it up again later should it become relevant / a priority.

2021-04-06 15:47 UTC, closed without merging