Replace URL with url-parse
dedis/cothority pull request #2394
Opened 2020-10-20 10:46 UTC by ineiti

As the dedis/cothority is not only used in the browser, but also in node
and nativescript, URL cannot be used reliably.

This PR replaces URL with the url-parse implementation.

2020-10-22 11:21 UTC, tharvik requested changes

2020-10-22 11:21 UTC, tharvik commented on external/js/cothority/src/network/websocket.ts
> +        if (url.hash !== "") {
```suggestion
        if (url.query !== "" || url.hash !== "") {
```

2020-10-22 13:54 UTC, tharvik commented
Hum, that's weird, it looks like the types definition for `url-parse` aren't correct. When using `new URL(..., true)`, `query` is indeed an object, but when `new URL(..., false)`, it is a `string` (which is the default behavior btw).. You can cast it to `unknown` before comparing, that should do it.

2020-10-23 13:27 UTC, tharvik commented on external/js/cothority/src/network/websocket.ts
> +        if (url.query !== undefined || url.hash !== "") {
The object is never `undefined`. The most precise test would be to check for the returned object size, which does works for both `string` and `Object`.

```suggestion
        if (Object.entries(url.query).length === 0 || url.hash !== "") {
```

2020-10-27 09:51 UTC, ineiti commented
Should work now - the condition was `=== 0` instead of `> 0`

2020-10-27 11:49 UTC, tharvik approved these changes

2020-10-27 11:49 UTC, merged