Updates @cothority/byzcoin import
dedis/cothority pull request #2405
Opened 2020-11-17 17:19 UTC by nkcr

In the beautifier I couldn't use ChainConfig for some strange reasons because it would fail the Calypso tests. This situation is fixed by changing the  ClientTransaction imports.

2020-11-17 18:06 UTC, ineiti commented
Nice catch! Any idea why that happened? I looked at it but couldn't see why this helps...

2020-11-17 19:31 UTC, nkcr commented
No idea, this is some kind of sorcery to me 🧙‍♂️.
I got this intuition because there were an error from calypso-rpc.ts saying that `ClientTransaction` were undefined.

2020-11-18 10:39 UTC, nkcr commented
Be aware that this change removes the default export of `ClientTransaction`. This change goes toward only using `index` for imports, which is something that already brought small incompatibility in the past when Linus made the change in some parts, without too much trouble (but a lot of frustration..).

2020-11-18 11:41 UTC, tharvik requested changes
You actually don't need to import from `[...]/byzcoin/index` but simply from `[...]/byzcoin`, as the `index.ts` is already exporting what's needed.

2020-11-18 13:42 UTC, ineiti commented
Waiting for cleanup of `/index` imports

2020-11-18 13:43 UTC, ineiti reviewed
Like @tharvik - remove the `/index` from the imports.

2020-11-18 16:43 UTC, ineiti commented on external/js/cothority/src/byzcoin/beautifier/config.ts
> +import { ChainConfig } from "../";
```suggestion
import { Argument, ChainConfig } from "../";
```

2020-11-18 16:48 UTC, tharvik requested changes
Can also you remove the dangling slash at the end of imports path?

2020-11-19 09:09 UTC, tharvik approved these changes

2020-11-19 10:29 UTC, merged