Add release workflow
dedis/cothority pull request #2420
Opened 2020-12-04 14:04 UTC by gnarula

Allows creating a release with built tarballs on pushing a tag

2020-12-04 14:24 UTC, ineiti approved these changes

2020-12-04 14:24 UTC, ineiti commented
I was wondering how you avoid having a release for every push. Wonderful `on: push: tag`!

2020-12-08 07:42 UTC, ineiti approved these changes

2020-12-08 07:44 UTC, ineiti requested changes
Thanks for the release action. Can you please add two more things to this PR?
- Update the `Versioning and Roadmap` section in cothority/README.md
- Update the cothority/PUBLISH.md file with instructions how and when to create new releases

To not create confusion between c4dt/byzcoin and the cothority releases, it might be worth thinking to reduce the cothority/conode.go to only include the things needed for evoting...

2020-12-17 09:48 UTC, ineiti commented
This PR should be rebased on master for the correct tests.

2020-12-17 15:29 UTC, gnarula commented
It turns out the tests depend on the other services. The way around it would be to decouple the tests from conode/conode.go which is well beyond the scope of this PR imho.

I'm thinking about undoing the last commit and work on the de-coupling of tests in another PR. What do you think @ineiti ?

2020-12-17 15:40 UTC, ineiti commented
One simple thing you can do: add a file `conode/full.go` with a compilation flag. Then you can compile the binary twice: once with the flag for the tests, once without the flag for the release.

2020-12-17 16:14 UTC, gnarula commented
thanks! SonarCloud complains but it's a false negative because of full.go

2020-12-17 16:33 UTC, ineiti commented
Coveralls is right ;) My idea was to have a `full.go` with only the imports. Then you can remove the `// +build !test` from `conode.go`...

```
// +build test

// Importing all necessary packages for tests
package main

import (
	_ "go.dedis.ch/cothority/v3/authprox"
	_ "go.dedis.ch/cothority/v3/byzcoin"
	_ "go.dedis.ch/cothority/v3/byzcoin/contracts"
	_ "go.dedis.ch/cothority/v3/calypso"
	_ "go.dedis.ch/cothority/v3/eventlog"
	_ "go.dedis.ch/cothority/v3/personhood"
	_ "go.dedis.ch/cothority/v3/skipchain"
)
```

2020-12-18 06:36 UTC, ineiti commented on PUBLISH.md
> +and push it to master with `git push origin vX.Y.Z`. A tag push would trigger
```suggestion
and push it to master with `git push origin vX.Y.Z`. A tag push triggers
```

2020-12-18 06:37 UTC, ineiti requested changes
Last corrections, then it's OK.

2020-12-18 06:37 UTC, ineiti commented on PUBLISH.md
> +the `release` action workflow with new release binaries available at
```suggestion
the `release` action workflow which releases new binaries in
```

2020-12-18 07:42 UTC, ineiti approved these changes

2020-12-18 07:42 UTC, merged