Fixes the pagination service
dedis/cothority pull request #2437
Opened 2021-03-17 12:11 UTC by nkcr

**What this PR does**

This PR updates the pagination service that is currently not implemented correctly. The pagination should allow clients to submit multiple requests to the same instance of a service, which is why it must use the same channels for each instance. This wasn't the case and it was also causing some goroutine leaks since the stopChan would be called only once, but a new stopChan was created each time.

2021-03-17 12:44 UTC, nkcr commented
Any of @ineiti @tharvik @cgrigis can review and merge.

2021-03-17 16:20 UTC, ineiti requested changes
There are several things I don't understand:
- why do you register the return result of `getPaginateService` to `RegisterStreamingHandlers`? From what I see, `getPaginateService` is called only once. So you don't need to use it as a callback here
- why should every call to `PaginateRequest` return the same channel? What happens if two clients connect at the same time and want to access two paginateservices?

Perhaps we should keep the meeting tomorrow, so that you can explain it to me ;)

2021-03-17 16:20 UTC, ineiti commented on byzcoin/streaming.go
> +// "statefull" service.
```suggestion
// "stateful" service.
```

2021-03-18 07:07 UTC, ineiti commented
> Discussion is welcome

OK, I re-sent the invite ;) I also invited @tharvik , as he's been working on this last month or so. I hope his memory is fresher than mine with regard to the streaming service...

2021-03-18 12:50 UTC, tharvik commented
Closed in favor of dedis/onet#674

2021-03-18 12:50 UTC, closed without merging